### ISSUE TITLE
showing inaccurate countdown

### ISSUE THREAD

**Issue by bharath-hebbar** [chribjel/isbunwindowsyet.com#3]
![image](https://github.com/chribjel/isbunwindowsyet.com/assets/66962257/f60d687e-5f92-4748-972d-9c6b4e0e0553)
![image](https://github.com/chribjel/isbunwindowsyet.com/assets/66962257/8cdabceb-af8d-4c44-ac30-a8ac1c755985)

above image shows system time in right bottom. on refresh count downs are different.

**Comment by bharath-hebbar** [comment]
seems like useeffect dependency array has setting multiple timeout function.

**Comment by Drylozu** [comment]
When `next build` is run, the output html contains the countdown but at build time. That will be the content on first load because there's a useState with this value by default.

https://github.com/chribjel/isbunwindowsyet.com/blob/446deb477203dfd666a38736dddfa9dc3dae25ea/src/app/BundowsCountdown.tsx#L6-L10

The only solutions are to render from the server with the current date (so you don't see a flashing between the date that is loaded first and when it is updated) or you can also set a different initial state so it updates everything when the user loads the page.

**Comment by bharath-hebbar** [comment]
> When `next build` is run, the output html contains the countdown but at build time. That will be the content on first load because there's a useState with this value by default.
> 
> https://github.com/chribjel/isbunwindowsyet.com/blob/446deb477203dfd666a38736dddfa9dc3dae25ea/src/app/BundowsCountdown.tsx#L6-L10
> 
> The only solutions are to render from the server with the current date (so you don't see a flashing between the date that is loaded first and when it is updated) or you can also set a different initial state so it updates everything when the user loads the page.

using server time also makes count down inaccurate because time zone are different for server cdn and user.
use dynamic = "force-dynamic" in page option may fix.

**Comment by chribjel** [comment]
Yes, i noticed this too late while i was on holiday, so i just removed it😅

Thanks for reporting though! @bharath-hebbar
